-- Migration number: 0001 	 2025-04-19T16:06:37.452Z
CREATE TABLE
	Users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		userName TEXT NOT NULL,
		passwordHash INTEGER NOT NULL,
		passwordSalt INTEGER NOT NULL
	);

CREATE TABLE
	Subjects (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		user INTEGER
	);

CREATE TABLE
	TestingSessions (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		location TEXT NOT NULL,
		test INTEGER NOT NULL,
		startTime DATETIME NOT NULL,
		endTime DATETIME NOT NULL
	);

CREATE TABLE
	Tests (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL
	);

CREATE TABLE
	Attempts (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user INTEGER NOT NULL
	);